### ISSUE TITLE
New NLog.Web.AspNetCore does not work in IIS production

### ISSUE THREAD

**Issue by sonphnt** [NLog/NLog.Web#122]
Hi Everyone,

I am using NLog.Extensions.Logging formerly and I worked perfevtly but since I switch to NLog.Web.AspNetCore. Logging is not working any more in IIS Production. It only work with local debug. I dont know why. Look at internal log and see there is a problem with ConnectionString

`Error when writing to database. Exception: System.InvalidOperationException: The ConnectionString property has not been initialized.
   at System.Data.SqlClient.SqlConnection.PermissionDemand()
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString)
   at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString)`

My old way is in Configure method. I load SQL connectionstring from appsettings.json
LogManager.Configuration.Variables["connectionString"] = Configuration.GetConnectionString("DefaultConnection");

And nlog.config file is in the same directory with web.config file.
What are exactly changes about this?

Thanks so much.

**Comment by sonphnt** [comment]
I have found the mistake of code ordering. We need to put AddNLog() above loading connectionstring.

loggerFactory.AddNLog();
app.AddNLogWeb();
            
LogManager.Configuration.Variables["connectionString"] = Configuration.GetConnectionString("DefaultConnection");

**Comment by 304NotModified** [comment]
thanks for feedback!
