### ISSUE TITLE
Crash on var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

### ISSUE THREAD

**Issue by hanslai** [NLog/NLog.Web#211]
I was upgrading NLog to Asp.net Core 2 by following [Getting started with ASP.NET Core 2](https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2)

but the program crash with an unhandled exception at the first line of program.cs 
**var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();**

With the following error message

```
System.MethodAccessException occurred
  HResult=0x80131510
  Message=Attempt by method 'NLog.Web.NLogBuilder.ConfigureNLog(NLog.Config.LoggingConfiguration)' to access method 'NLog.LogManager.get_LogFactory()' failed.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at NLog.Web.NLogBuilder.ConfigureNLog(LoggingConfiguration configuration)
   at example.API.Program.Main(String[] args) in D:\SourceCode\example\example.API\Program.cs:line 13
```

```
var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();  // crash here
try
{
   logger.Debug("init main");
   BuildWebHost(args).Run();
}
catch (Exception e)
{
   //NLog: catch setup errors
   logger.Error(e, "Stopped program because of logger exception");
   throw;
}
```

**Here is the .csproj file**
```
<ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="3.0.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="7.2.0" />
    <PackageReference Include="NLog" Version="5.0.0-beta11" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.5.0-beta03" />
    <PackageReference Include="NWebsec.AspNetCore.Middleware" Version="1.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
  </ItemGroup>
```

```
<ItemGroup>
    <Content Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
</ItemGroup>
```
  
**Here is the nlog.config file**

```
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="log\internal-nlog.txt">


  <!-- the targets to write to -->
  <targets>
    <!-- write logs to file -->
    <target xsi:type="File" name="allfile" fileName="log\nlog-all-${shortdate}.log"
                layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|${message} ${exception}" />

    <!-- another file log, only own logs. Uses some ASP.NET core renderers -->
    <target xsi:type="File" name="ownFile-web" fileName="log\nlog-AIS-${shortdate}.log"
            layout="${longdate}|${event-properties:item=EventId.Id}|${logger}|${uppercase:${level}}|  ${message} ${exception}|url: ${aspnet-request-url}|action: ${aspnet-mvc-action}" />

    <!-- write to the void aka just remove -->
    <target xsi:type="Null" name="blackhole" />
  </targets>

  <!--
  Log Level:	  Example
  Fatal:	      Highest level: important stuff down
  Error:	      For example application crashes / exceptions.
  Warn:	        Incorrect behavior but the application can continue
  Info:	        Normal behavior like mail sent, user updated profile etc.
  Debug:	      Executed queries, user authenticated, session expired
  Trace:	      Begin method X, end method X etc
   -->

  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Info" writeTo="allfile" />

    <!--Skip Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" minlevel="Info" writeTo="blackhole" final="true" />
    <logger name="*" minlevel="Info" writeTo="ownFile-web" />
  </rules>
</nlog>
```

**Comment by 304NotModified** [comment]
This is probably a wrong version of one of the dependencies. Please post the following:

- your platform
- versions of NLog, NLog.web.aspnetcore and NLog.extensions.logging. 

Thx!

**Comment by 304NotModified** [comment]
I think updating to https://www.nuget.org/packages/NLog.Web.AspNetCore/4.5.0-beta04 solves your problem!

**Comment by codetian** [comment]
I has updated NLog.Web 
```
 <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.0" />
    <PackageReference Include="NLog" Version="5.0.0-beta11" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.5.0-beta04" />
  </ItemGroup>
```
 but the program crash with an unhandled exception at the first line of program.cs
var logger = NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();

**Comment by codetian** [comment]
platfrom : netcore 2.0
NLog : 5.0.0-beta11
NLog.Web.AspNetCore :4.5.0-beta04

**Comment by 304NotModified** [comment]
Funny, it should not compile. 

Please move to from NLog 5 beta to NLog 4.5 beta, see dependencies of NLog.extensions.logging.

**Comment by 304NotModified** [comment]
I assume your question has been answered, if not, let us know!

**Comment by superbabesliders** [comment]
I got the same problem with NLog 5.0.0-beta11.
I changed to the version 4.5.0-beta07 and that's solved the problem for me.
Thank you
