### ISSUE TITLE
Bug in Tutorial for ASP.NET-CORE-2?

### ISSUE THREAD

**Issue by ssczo** [NLog/NLog.Web#218]
I used the tutorial on:
https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2

I enabled exception:
```
     throwExceptions="true"
      throwConfigExceptions="true"
```
With that you will get some errors like:

> ArgumentException: LayoutRenderer cannot be found: 'aspnet-request-url'. Is NLog.Web not included?

It looks like  {aspnet-request-url} are not supported {aspnet-mvc-action}

**Comment by ssczo** [comment]
See versions:

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="NLog" Version="4.5.0-beta08" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.5.0-beta04" />
  </ItemGroup>


Im Working on a machine with Windows 10 Pro 64Bit

There is no NLog.Extensions.Logging

**Comment by 304NotModified** [comment]
could you please post the full internal log on trace level?

**Comment by 304NotModified** [comment]
could you please post the full internal log on trace level?

> I'm Working on a machine with Windows 10 Pro 64Bit

I have the same platform, works for me. The only difference is "Microsoft.AspNetCore.All" Version="2.0.3"

> There is no NLog.Extensions.Logging

It's a dependency of NLog.Web.AspNetCore

> What's your .NET platform and OS platform?

ASP.NET Core 2 on .NET Core? Or .NET 4.6?

**Comment by ssczo** [comment]
2017-11-23 15:30:14.5571 Debug ScanAssembly('NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c')
2017-11-23 15:30:14.6288 Debug Start auto loading, location: C:\Users\ssc\.nuget\packages\nlog\4.5.0-beta08\lib\netstandard2.0
2017-11-23 15:30:14.6288 Debug Auto loading done
2017-11-23 15:30:14.6288 Info Message Template Auto Format enabled
2017-11-23 15:30:14.6494 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.6494 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.6585 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-11-23 15:30:14.6814 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2017-11-23 15:30:14.6814 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.6814 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.6814 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.6814 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.6814 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.6814 Trace  Scanning Property Inner 'SimpleLayout=Layout Renderer: ${level}' NLog.Layouts
2017-11-23 15:30:14.6814 Trace  Scanning SimpleLayout 'SimpleLayout=Layout Renderer: ${level}'
2017-11-23 15:30:14.6874 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.6874 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.6874 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.6874 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.6874 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.6874 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.7032 Debug Setting 'FileTarget.name' to 'allfile'
2017-11-23 15:30:14.7032 Debug Setting 'FileTarget.fileName' to 'c:\temp\nlog-all-${shortdate}.log'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning ShortDateLayoutRenderer 'Layout Renderer: ${shortdate}'
2017-11-23 15:30:14.7032 Debug Setting 'FileTarget.layout' to '${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.7032 Debug Setting 'EventPropertiesLayoutRenderer.item' to 'EventId.Id'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-properties}'
2017-11-23 15:30:14.7032 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.7032 Debug Setting 'UppercaseLayoutRendererWrapper.Inner' to '${level}'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.7032 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.7032 Trace  Scanning Property Inner ''${level}'' NLog.Layouts
2017-11-23 15:30:14.7032 Trace  Scanning SimpleLayout ''${level}''
2017-11-23 15:30:14.7032 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.7032 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.7032 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7032 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.7279 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7279 Trace Scanning ExceptionLayoutRenderer 'Layout Renderer: ${exception}'
2017-11-23 15:30:14.7279 Trace  Scanning Property Formats 'System.Collections.Generic.List`1[NLog.Config.ExceptionRenderingFormat]' System.Collections.Generic
2017-11-23 15:30:14.7279 Info Adding target File Target[allfile]
2017-11-23 15:30:14.7279 Debug Registering target allfile: NLog.Targets.FileTarget
2017-11-23 15:30:14.7279 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7279 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.7279 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-11-23 15:30:14.7335 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.7335 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.7335 Trace  Scanning Property Inner 'SimpleLayout=Layout Renderer: ${level}' NLog.Layouts
2017-11-23 15:30:14.7335 Trace  Scanning SimpleLayout 'SimpleLayout=Layout Renderer: ${level}'
2017-11-23 15:30:14.7335 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.7335 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.7335 Debug Setting 'FileTarget.name' to 'requestOnly'
2017-11-23 15:30:14.7335 Debug Setting 'FileTarget.fileName' to 'c:\temp\nlog-requestOnly-${shortdate}.log'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning ShortDateLayoutRenderer 'Layout Renderer: ${shortdate}'
2017-11-23 15:30:14.7335 Debug Setting 'FileTarget.layout' to '${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|--->${message}  ${aspnet-mvc-action} ${aspnet-request-url} ${exception}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.7335 Debug Setting 'EventPropertiesLayoutRenderer.item' to 'EventId.Id'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-properties}'
2017-11-23 15:30:14.7335 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.7335 Debug Setting 'UppercaseLayoutRendererWrapper.Inner' to '${level}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.7335 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.7335 Trace  Scanning Property Inner ''${level}'' NLog.Layouts
2017-11-23 15:30:14.7335 Trace  Scanning SimpleLayout ''${level}''
2017-11-23 15:30:14.7335 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.7335 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.7335 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.7335 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.8325 Warn Error when setting property 'Layout' on 'File Target[requestOnly]' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-mvc-action'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
2017-11-23 15:30:14.8586 Warn Error when setting '${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|--->${message}  ${aspnet-mvc-action} ${aspnet-request-url} ${exception}' on attibute 'layout'
2017-11-23 15:30:14.8831 Error Parsing configuration from C:\Users\ssc\source\repos\Xyz.Logger\Xyz.Logger.Demo\bin\Debug\netcoreapp2.0\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\Users\ssc\source\repos\Xyz.Logger\Xyz.Logger.Demo\bin\Debug\netcoreapp2.0\NLog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'Layout' on File Target[requestOnly] ---> System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-mvc-action'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
2017-11-23 15:30:14.9734 Debug Loading config from C:\Users\ssc\source\repos\Xyz.Logger\Xyz.Logger.Demo\bin\Debug\netcoreapp2.0\NLog.config
2017-11-23 15:30:14.9734 Trace ParseNLogElement
2017-11-23 15:30:14.9734 Info Message Template Auto Format enabled
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.9734 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-11-23 15:30:14.9734 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.9734 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.9734 Trace  Scanning Property Inner 'SimpleLayout=Layout Renderer: ${level}' NLog.Layouts
2017-11-23 15:30:14.9734 Trace  Scanning SimpleLayout 'SimpleLayout=Layout Renderer: ${level}'
2017-11-23 15:30:14.9734 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.9734 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.9734 Debug Setting 'FileTarget.name' to 'allfile'
2017-11-23 15:30:14.9734 Debug Setting 'FileTarget.fileName' to 'c:\temp\nlog-all-${shortdate}.log'
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning ShortDateLayoutRenderer 'Layout Renderer: ${shortdate}'
2017-11-23 15:30:14.9734 Debug Setting 'FileTarget.layout' to '${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|${message} ${exception}'
2017-11-23 15:30:14.9734 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9734 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.9734 Debug Setting 'EventPropertiesLayoutRenderer.item' to 'EventId.Id'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-properties}'
2017-11-23 15:30:14.9839 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.9839 Debug Setting 'UppercaseLayoutRendererWrapper.Inner' to '${level}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.9839 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.9839 Trace  Scanning Property Inner ''${level}'' NLog.Layouts
2017-11-23 15:30:14.9839 Trace  Scanning SimpleLayout ''${level}''
2017-11-23 15:30:14.9839 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.9839 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning ExceptionLayoutRenderer 'Layout Renderer: ${exception}'
2017-11-23 15:30:14.9839 Trace  Scanning Property Formats 'System.Collections.Generic.List`1[NLog.Config.ExceptionRenderingFormat]' System.Collections.Generic
2017-11-23 15:30:14.9839 Info Adding target File Target[allfile]
2017-11-23 15:30:14.9839 Debug Registering target allfile: NLog.Targets.FileTarget
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.9839 Debug Setting 'UppercaseLayoutRendererWrapper.uppercase' to 'true'
2017-11-23 15:30:14.9839 Trace Wrapping LevelLayoutRenderer with UppercaseLayoutRendererWrapper
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.9839 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.9839 Trace  Scanning Property Inner 'SimpleLayout=Layout Renderer: ${level}' NLog.Layouts
2017-11-23 15:30:14.9839 Trace  Scanning SimpleLayout 'SimpleLayout=Layout Renderer: ${level}'
2017-11-23 15:30:14.9839 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.9839 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:14.9839 Debug Setting 'FileTarget.name' to 'requestOnly'
2017-11-23 15:30:14.9839 Debug Setting 'FileTarget.fileName' to 'c:\temp\nlog-requestOnly-${shortdate}.log'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9839 Trace Scanning ShortDateLayoutRenderer 'Layout Renderer: ${shortdate}'
2017-11-23 15:30:14.9839 Debug Setting 'FileTarget.layout' to '${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|--->${message}  ${aspnet-mvc-action} ${aspnet-request-url} ${exception}'
2017-11-23 15:30:14.9839 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9998 Trace Scanning LongDateLayoutRenderer 'Layout Renderer: ${longdate}'
2017-11-23 15:30:14.9998 Debug Setting 'EventPropertiesLayoutRenderer.item' to 'EventId.Id'
2017-11-23 15:30:14.9998 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9998 Trace Scanning EventPropertiesLayoutRenderer 'Layout Renderer: ${event-properties}'
2017-11-23 15:30:14.9998 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.9998 Debug Setting 'UppercaseLayoutRendererWrapper.Inner' to '${level}'
2017-11-23 15:30:14.9998 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9998 Trace Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9998 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9998 Trace Scanning UppercaseLayoutRendererWrapper 'Layout Renderer: ${uppercase}'
2017-11-23 15:30:14.9998 Trace  Scanning Property Culture '' System.Globalization
2017-11-23 15:30:14.9998 Trace  Scanning Property Inner ''${level}'' NLog.Layouts
2017-11-23 15:30:14.9998 Trace  Scanning SimpleLayout ''${level}''
2017-11-23 15:30:14.9998 Trace   Scanning Property Renderers 'System.Collections.ObjectModel.ReadOnlyCollection`1[NLog.LayoutRenderers.LayoutRenderer]' System.Collections.ObjectModel
2017-11-23 15:30:14.9998 Trace   Scanning LevelLayoutRenderer 'Layout Renderer: ${level}'
2017-11-23 15:30:14.9998 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9998 Trace Scanning LoggerNameLayoutRenderer 'Layout Renderer: ${logger}'
2017-11-23 15:30:14.9998 Trace FindReachableObject<NLog.Internal.IRenderable>:
2017-11-23 15:30:14.9998 Trace Scanning MessageLayoutRenderer 'Layout Renderer: ${message}'
2017-11-23 15:30:15.0581 Warn Error when setting property 'Layout' on 'File Target[requestOnly]' Exception: System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-mvc-action'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
2017-11-23 15:30:15.0816 Warn Error when setting '${longdate}|${event-properties:item=EventId.Id}|${uppercase:${level}}|${logger}|--->${message}  ${aspnet-mvc-action} ${aspnet-request-url} ${exception}' on attibute 'layout'
2017-11-23 15:30:15.1077 Error Parsing configuration from C:\Users\ssc\source\repos\Xyz.Logger\Xyz.Logger.Demo\bin\Debug\netcoreapp2.0\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\Users\ssc\source\repos\Xyz.Logger\Xyz.Logger.Demo\bin\Debug\netcoreapp2.0\NLog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'Layout' on File Target[requestOnly] ---> System.ArgumentException: LayoutRenderer cannot be found: 'aspnet-mvc-action'. Is NLog.Web not included?
   at NLog.Config.Factory`2.CreateInstance(String name)
   at NLog.Layouts.LayoutParser.GetLayoutRenderer(ConfigurationItemFactory configurationItemFactory, String name)
   at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader)
   at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
   at NLog.Layouts.SimpleLayout.set_Text(String value)
   at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---

**Comment by ssczo** [comment]
We are using ASP.NET Core 2 on .NET Core"

>  have the same platform, works for me. The only difference is "Microsoft.AspNetCore.All" Version="2.0.3"

Which version do you have?

**Comment by 304NotModified** [comment]
2.0.0, see https://github.com/NLog/NLog.Web/blob/master/examples/ASP.NET%20Core%202/Visual%20Studio%202017/ASP.NET%20Core%202%20-%20VS2017/ASP.NET%20Core%202%20-%20VS2017.csproj

**Comment by ssczo** [comment]
The only difference I see is the Startup:
See Configure:
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddNLog();
            loggerFactory.ConfigureNLog("NLog.config");     
            LogManager.Configuration.Variables["connectionString"] = Configuration.GetConnectionString("myDb");
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseMvc();
        }

**Comment by 304NotModified** [comment]
that's a big difference with the tutorial:

https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2#4-update-programcs

```
public static void Main(string[] args)
{
    // NLog: setup the logger first to catch all errors
    var logger = NLogBuilder.ConfigureNLog("NLog.config").GetCurrentClassLogger();
    try
    {
        logger.Debug("init main");
        BuildWebHost(args).Run();
    }
    catch (Exception e)
    {
        //NLog: catch setup errors
        logger.Error(e, "Stopped program because of exception");
        throw;
    }
}

public static IWebHost BuildWebHost(string[] args) =>
    WebHost.CreateDefaultBuilder(args)
        .UseStartup<Startup>()
        .UseNLog() // NLog: setup NLog for Dependency injection
        .Build();
```

**Comment by ssczo** [comment]
Ok sorry about that trouble. You can close it. I found a lot of different version how to use nlog. I used one which is also running. I had only problems with these two   {aspnet-request-url}  ....

**Comment by 304NotModified** [comment]
in the old way you need to registeren nlog.web.aspnetcore manual. That's fixed with the `NLogBuilder` :)

**Comment by AuthorProxy** [comment]
The same bug and still no answer
