### ISSUE TITLE
Cannot access the constructor of type: NLog.Web.LayoutRenderers.AspNetRequestValueLayoutRenderer. Is the required permission granted?

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#34]
```
NLog.NLogConfigurationException was unhandled by user code
  HResult=-2146233088
  Message=Cannot access the constructor of type: NLog.Web.LayoutRenderers.AspNetRequestValueLayoutRenderer. Is the required permission granted?
  Source=NLog
  StackTrace:
       at NLog.Internal.FactoryHelper.CreateInstance(Type t)
       at NLog.Config.Factory`2.TryCreateInstance(String itemName, TBaseType& result)
       at NLog.Config.Factory`2.CreateInstance(String name)
       at NLog.Layouts.LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr)
       at NLog.Layouts.LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Boolean isNested, String& text)
       at NLog.Layouts.SimpleLayout.set_Text(String value)
       at NLog.Layouts.SimpleLayout..ctor(String txt, ConfigurationItemFactory configurationItemFactory)
       at NLog.Internal.PropertyHelper.TryNLogSpecificConversion(Type propertyType, String value, Object& newValue, ConfigurationItemFactory configurationItemFactory)
       at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
       at NLog.Config.XmlLoggingConfiguration.ConfigureObjectFromAttributes(Object targetObject, NLogXmlElement element, Boolean ignoreType)
       at NLog.Config.XmlLoggingConfiguration.ParseTargetElement(Target target, NLogXmlElement targetElement)
       at NLog.Config.XmlLoggingConfiguration.ParseTargetsElement(NLogXmlElement targetsElement)
       at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(NLogXmlElement nlogElement, String filePath, Boolean autoReloadDefault)
       at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
       at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
       at NLog.Config.XmlLoggingConfiguration..ctor(String fileName, Boolean ignoreErrors)
       at NLog.Extensions.Logging.AspNetExtensions.ConfigureNLog(String fileName)
       at NLog.Extensions.Logging.AspNetExtensions.ConfigureNLog(IHostingEnvironment env, String configFileRelativePath)
       at aspnet5application.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory) in X:\_github\nlog\NLog.Framework.logging\examples\aspnet5application\src\aspnet5application\Startup.cs:line 50
  InnerException: 

```

**Comment by 304NotModified** [comment]
Got this error and need DI?

See http://stackoverflow.com/a/42101946/201303
