### ISSUE TITLE
POST response becomes A non-empty request body is required after using NLog

### ISSUE THREAD

**Issue by StevenLiSiwei** [NLog/NLog.Web#399]
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

QUESTIONS are preferred on StackOverflow. You could expect a faster response there (but do include all the info below). Use the tag "nlog" https://stackoverflow.com/questions/ask

Please only post issues here related to NLog.Web. If unsure, please post on https://github.com/NLog/NLog/issues/new

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):

**- Bug**

**NLog version**: 4.5.11

**NLog.Web/NLog.Web.AspNetCore version**: 
4.8.1

**NLog.Extensions.Logging version**: 
N.A

**Platform**: .NET Core 2 

**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      throwConfigExceptions="true"
      internalLogLevel="info"
      internalLogFile="nlog.log">


  <targets async="true">
    <!-- for DB -->
    <target name="db" xsi:type="Database">
      <dbProvider>MySql.Data.MySqlClient.MySqlConnection, MySql.Data</dbProvider>
      <connectionString>secret</connectionString>
      <commandText>
        INSERT INTO lcs_log.log(level, activity_id, callsite, session,
        cookie, host, method, referrer, user_agent, url, request,
        response, is_auth, user_identity, exception) VALUES(@level,
        @activity_id,@callsite,@session, @cookie, @host, @method,
        @referrer, @user_agent, @url,@request, @response,
        @is_auth, @user_identity, @exception);
      </commandText>
      <!--<commandText>
        INSERT INTO lcs_log.log(level) VALUES('@level');
      </commandText>-->
      <parameter name="@level" layout="${level}" />
      <parameter name="@activity_id" layout="${activityid}" />
      <parameter name="@callsite" layout="${callsite}"/>
      <parameter name="@session" layout="${aspnet-session:Variable=Username}" />
      <parameter name="@cookie" layout="${aspnet-request-cookie:CookieNames=username}" />
      <parameter name="@host" layout="${aspnet-request-host}" />
      <parameter name="@method" layout="${aspnet-request-method}" />
      <parameter name="@referrer" layout="${aspnet-request-referrer}" />
      <parameter name="@user_agent" layout="${aspnet-request-useragent}" />
      <parameter name="@url" layout="${aspnet-request-url:IncludePort=true:IncludeQueryString=true}" />
      <parameter name="@request" layout="${aspnet-request-posted-body}" />
      <parameter name="@response" layout="${aspnet-item:variable=response}" />
      <parameter name="@is_auth" layout="${aspnet-user-isAuthenticated}" />
      <parameter name="@user_identity" layout="${aspnet-user-identity}" />
      <parameter name="@exception" layout="${message:format=toString,Data}" />
    </target>

  </targets>



  <!-- rules to map from logger name to target -->
  <rules>
    <!--All logs, including from Microsoft-->
    <logger name="*" minlevel="Trace" writeTo="db" />

    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxlevel="Info" final="true" />
    <!-- BlackHole -->
  </rules>
</nlog>

```

In case of a BUG:

- What is the current result?
POST action with object
server will reply 400 Bad Request with the following josn
`{
    "": [
        "A non-empty request body is required."
    ]
  }`

- What is the expected result?
server responses with processed object

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
```
2019-04-22 23:19:06.9259 Info Found 55 configuration items
2019-04-22 23:19:09.5623 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:09.5623 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:09.5961 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:09.5989 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'HttpRequestStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<ValidateState>g__ThrowObjectDisposedException|28_0()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:09.5989 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:09.7855 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:09.7855 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.2682 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.2995 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.3382 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.3382 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.3382 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.3539 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.3539 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:41.3539 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:49.2183 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:49.2600 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:50.0413 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:50.0413 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:50.0413 Warn Exception in layout renderer. Exception: System.InvalidOperationException: Session has not been configured for this application or request.
   at Microsoft.AspNetCore.Http.DefaultHttpContext.get_Session()
   at NLog.Web.LayoutRenderers.AspNetSessionValueLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2019-04-22 23:19:50.0413 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
```

- Please post full exception details (message, stacktrace, inner exceptions)
There is not exception but it happens in Nlog internal log
- Are there any workarounds? yes/no
Yes. as soon as I disabled Nlog in startup the bug is gone
- Is there a version in which it did work? 
This is the first time we switched from .Net Framework to .Net Core
- Can you help us by writing an unit test?
I try to put .UseNlog() in different order, but it is not working. I've used Sentry as well.
```csharp
public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .UseKestrel()
                .ConfigureLogging(logging =>
                {
                    logging.ClearProviders();
                    logging.SetMinimumLevel(LogLevel.Trace);
                })
                .UseNLog()
                .UseSentry(options =>
                {
                    options.Dsn = "secret";
                    options.IncludeRequestPayload = true;
                    options.SendDefaultPii = true;
                    options.IncludeActivityData = true;
                    options.MinimumBreadcrumbLevel = LogLevel.Information;
                    options.MinimumEventLevel = LogLevel.Warning;
                    options.AttachStacktrace = true;
                    options.DiagnosticsLevel = SentryLevel.Error;
                    // The parameter 'options' here has values populated through the configuration system.
                    // That includes 'appsettings.json', environment variables and anything else
                    // defined on the ConfigurationBuilder.
                    // See: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-2.1&tabs=basicconfiguration
                    // Tracks the release which sent the event and enables more features: https://docs.sentry.io/learn/releases/
                    // If not explicitly set here, the SDK attempts to read it from: AssemblyInformationalVersionAttribute and AssemblyVersion
                    // TeamCity: %build.vcs.number%, VSTS: BUILD_SOURCEVERSION, Travis-CI: TRAVIS_COMMIT, AppVeyor: APPVEYOR_REPO_COMMIT, CircleCI: CIRCLE_SHA1
                    //options.Release = "e386dfd"; // Could be also the be like: 2.0 or however your version your app

                    options.MaxBreadcrumbs = 200;

                    // Set a proxy for outgoing HTTP connections
                    options.HttpProxy = null; // new WebProxy("https://localhost:3128");

                    // Example: Disabling support to compressed responses:
                    options.DecompressionMethods = DecompressionMethods.None;

                    options.MaxQueueItems = 100;
                    options.ShutdownTimeout = TimeSpan.FromSeconds(10);
                })
                .UseUrls("http://*:5000");   
```

In case of a FEATURE REQUEST:
 
 - Why do we need it?
 - An example of the XML config, if relevant.

**Comment by snakefoot** [comment]
The ObjectDisposedException exception looks interesting. So there is an active request but the stream has been closed:

```
2019-04-22 23:19:09.5989 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'HttpRequestStream'.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.<ValidateState>g__ThrowObjectDisposedException|28_0()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadToEnd()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)

2019-04-22 23:19:41.3539 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)

2019-04-22 23:19:50.0413 Warn Exception in layout renderer. Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.get_Position()
   at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
   at NLog.Web.LayoutRenderers.AspNetRequestPostedBody.DoAppend(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
```

Since NLog doesn't dispose its StreamReader (eventhough it should) and there is no Finalizer for StreamReader.  One might consider updating NLog to call dispose on StreamReader (but use constructor to leave underlying stream open).

https://stackoverflow.com/questions/52946747/how-to-get-httprequest-body-in-net-core?noredirect=1&lq=1

At what point in your code are doing the logging? Are you starting a new async task based on the original request, which is logging? (Recall that Asp.Net.Core is very aggressive about reusing HttpRequest-objects)

**Comment by snakefoot** [comment]
But it looks like this StackOverflow matches the error `"A non-empty request body is required."`

Where it says one is required to call `HttpRequest.EnableRewind();` before accessing `Body`-property:

https://stackoverflow.com/questions/52931906/asp-net-core-log-all-requests-reading-body-twice-enablerewind-not-working-for

**Comment by StevenLiSiwei** [comment]
@snakefoot Thanks for looking into this issue.

`At what point in your code are doing the logging? Are you starting a new async task based on the original http-request, which is then doing logging? (Recall seeing that Asp.Net.Core is very aggressive about recycling its HttpRequest-objects)1`

As you can see from the NLog config file. All my api code are sync.  I created a middle-ware initially to catch request api before entering to controllers using NLog, I was getting the error "A non-empty request body is required.".  So I totally removed it and only leave NLog in dependency injection part. However, I am still getting the error. So as soon as I remove UseNlog in dependency injection part. The server is working fine.

**Comment by snakefoot** [comment]
>As you can see from the NLog config file. All my api code are sync

The `NLog.config`-file doesn't show the logic you have implemented for doing logging .

**Comment by 304NotModified** [comment]
PS:

> One might consider updating NLog to call dispose on StreamReader (but use constructor to leave underlying stream open).

Disposing the streamreader would dispose the stream. I newer platforms you could influence that with a parameter, but then the dispose of the streamreader is a NOOP ;)

**Comment by snakefoot** [comment]
Created #401 with additional checking of HttpRequest.ContentLength

**Comment by snakefoot** [comment]
@StevenLiSiwei Could you try this pre-release build to see if it fixes the error when making request with empty body:

https://ci.appveyor.com/project/nlog/nlog-web/builds/24144098/artifacts

Download `NLog.Web.AspNetCore.4.8.1.1157-PR401.nupkg`

**Comment by StevenLiSiwei** [comment]
@snakefoot , I downloaded your pre-release nuget, and I still faces the issue. the screenshot is below:
<img align="left" src="https://imgur.com/g28Ck74">

**Comment by 304NotModified** [comment]
Please check, if only ${aspnet-request-posted-body} is removed from your config, then NLog should work.

**Comment by snakefoot** [comment]
@StevenLiSiwei Could you try to setup a middleware in your application that only does this:

```
public void Invoke(HttpContext context)
{
   context.Request.EnableRewind();
   logger.LogInformation("EnableRewind");
}
```

**Comment by snakefoot** [comment]
@StevenLiSiwei Could you try this updated build:

https://ci.appveyor.com/project/nlog/nlog-web/builds/24234072/artifacts

Download NLog.Web.AspNetCore.4.8.1.1167-PR401.nupkg (Created from #401)

**Comment by snakefoot** [comment]
@StevenLiSiwei Could you try this updated build:

https://ci.appveyor.com/project/nlog/nlog-web/builds/24235793/artifacts

Download NLog.Web.AspNetCore.4.8.1.1170-PR401.snupkg (Created from #401)

**Comment by StevenLiSiwei** [comment]
> @StevenLiSiwei
> 
> Please check, if only ${aspnet-request-posted-body} is removed from your config, then NLog should not break your application.

@304NotModified 

Yes. Once I changed ${aspnet-request-posted-body} to ${aspnet-item:variable=request}. the 
> A non-empty request body is required 
disappeared and everything is working. However no request body is logged. 

![nlog issue 3](https://user-images.githubusercontent.com/9862466/57077703-4923af80-6d1f-11e9-84b0-e2b2aaea94e0.JPG)

**Comment by StevenLiSiwei** [comment]
> @StevenLiSiwei Could you try this updated build:
> 
> https://ci.appveyor.com/project/nlog/nlog-web/builds/24242308/artifacts
> 
> Download NLog.Web.AspNetCore.4.8.1.1184-PR401.nupkg (Created from #401)

Amazing !!! it is working now.

**Comment by snakefoot** [comment]
> @StevenLiSiwei Amazing !!! it is working now.

Happy to hear. Would it be possible for you to verify that it also works for standard ASP.NET without NetCore ?

**Comment by StevenLiSiwei** [comment]
> > @StevenLiSiwei Amazing !!! it is working now.
> 
> Happy to hear. Would it be possible for you to verify that it also works for standard ASP.NET without NetCore ?

The Nuget I replaced are only NLog.Web.AspNetCore. Can you let me know how I can do it for ASP.NET  ?

**Comment by snakefoot** [comment]
The same build:

https://ci.appveyor.com/project/nlog/nlog-web/builds/24242308/artifacts

Also contains the artifact: NLog.Web.4.8.1.1184-PR401.nupkg (Download and use for ASP.NET)

**Comment by snakefoot** [comment]
@StevenLiSiwei There is now this available:

https://www.nuget.org/packages/NLog.Web.AspNetCore/4.8.2-rc1

**Comment by 304NotModified** [comment]
Releasing 4.8.2 for ASP.NET Core, so this is fixed

**Comment by StevenLiSiwei** [comment]
@snakefoot @304NotModified Thanks for your help.

**Comment by snakefoot** [comment]
@StevenLiSiwei Thank you for testing and being patient :)

**Comment by snakefoot** [comment]
Thanks to @bakgerman now NLog.Web.AspNetCore v5.1 re-introduces [${aspnet-request-posted-body}](https://github.com/NLog/NLog/wiki/AspNet-Request-posted-body-layout-renderer) with help from middleware:
```c#
app.UseMiddleware<NLog.Web.NLogRequestPostedBodyMiddleware>();
```
It is no longer necessary to explicit call `context.Request.EnableBuffering();` as it is handled by the middleware.
