### ISSUE TITLE
LogManager.Configuration.Variables throws in high traffic

### ISSUE THREAD

**Issue by nibblesnbits** [NLog/NLog.Web#464]
**Type**: Bug

**NLog version**: 4.5.10

**NLog.Web/NLog.Web.AspNetCore version**:  4.7.0

**Platform**: .NET Core 2.2

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="info"
      internalLogFile="C:\tmp\nlog\internal.txt">

  <extensions>
    <add assembly="NLog.Web.AspNetCore" />
  </extensions>

  <targets>
    <target xsi:type="File" name="web" fileName=".\logs\${shortdate}.log"
            layout="${longdate}|${var:requestId}|${uppercase:${level}}|${message} ${exception:format=tostring}|url: ${aspnet-request-url}" />
  </targets>

  <rules>

    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <logger name="*" minlevel="Trace" writeTo="web" />
  </rules>
</nlog>
```

- What is the current result?
  **Exception** 2019-09-17 13:57:57.8658||ERROR|Connection id "0HLPREORAFF1D", Request id "0HLPREORAFF1D:00000003": An unhandled exception was thrown by the application. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Ecp.CmsApi.Startup.<>c.<Configure>b__6_0(HttpContext c, Func`1 n) in /home/vsts/work/1/s/EcpCmsApiFacade/EcpCmsApiFacade/Startup.cs:line 167
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)|url: http://api.ecpinc.net/js/main.chunk.js

- What is the expected result? 
Setting of a configuration variable succeeds
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Currently Unable
- Please post full exception details (message, stacktrace, inner exceptions)
2019-09-17 13:57:57.8658||ERROR|Connection id "0HLPREORAFF1D", Request id "0HLPREORAFF1D:00000003": An unhandled exception was thrown by the application. System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Ecp.CmsApi.Startup.<>c.<Configure>b__6_0(HttpContext c, Func`1 n) in /home/vsts/work/1/s/EcpCmsApiFacade/EcpCmsApiFacade/Startup.cs:line 167
   at Microsoft.AspNetCore.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__1(HttpContext context)
   at Microsoft.AspNetCore.HostFiltering.HostFilteringMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)|url: http://api.ecpinc.net/js/main.chunk.js

- Are there any workarounds? yes/no
Unkown
- Is there a version in which it did work? 
No
- Can you help us by writing an unit test?
Not sure how to replicate this in a unit test

**NOTES**

The code causing this is pretty simple:

```cs
public void Configure(IApplicationBuilder app, IHostingEnvironment env) {

            app.Use((c, n) => {
                // the line below throws
                LogManager.Configuration.Variables["requestId"] = Guid.NewGuid().ToString("n");
                return n();
            });

```

I'm guessing if `LogManager.Configuration.Variables` is changed to a `System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>` this issue would go away, but that's probably a non-trivial change.  It only occurs on my production server when there's far more traffic.

**Comment by snakefoot** [comment]
There has been a changed to NLog Config Variables with NLog ver. 4.6.4. See also #3430

**Comment by snakefoot** [comment]
@nibblesnbits But it looks like you are trying to save the RequestId from HttpContext in the global NLog Config Variable. This will not work if you have an application that handles more than one HttpRequest at a time (Cannot have two requestids in the same global variable).

I would suggest that you make use of MEL-BeginScope or NLog [MappedDiagnosticsLogicalContext](https://github.com/NLog/NLog/wiki/LogEvent-Context-Information#mappeddiagnosticslogicalcontext).

An even better approach for capturing HttpContext-information is to make use of the army of [${aspnet}](https://nlog-project.org/config/?tab=layout-renderers&search=package:nlog.web.aspnetcore)-layoutrenderers in your NLog-target-output.

**Comment by snakefoot** [comment]
Reading the [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write) for ASP.NET Core. Then you could also do this:

```c#
        app.Use(async (context, next) =>
        {
            context.Items["requestId"] = Guid.NewGuid().ToString("n");
            // Call the next delegate/middleware in the pipeline
            await next();
        });
```

Then add [${aspnet-item:variable=requestId}](https://github.com/NLog/NLog/wiki/AspNetItem-layout-renderer) to your NLog target ouput.

**Comment by nibblesnbits** [comment]
I'll give these options a shot.  I'm thinking all I need is the ${aspnet-traceidentifier}, actually, so thank you so much.
