### ISSUE TITLE
Coverage calculation broken

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#470]
> No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
OpenCover\tools\OpenCover.Console.exe -register:user -returntargetcode -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"\"c:\projects\nlogweb\tests\NLog.Web.AspNetCore.Tests\bin\Release\net461\NLog.Web.AspNetCore.Tests.dll\" -appveyor -noshadow" -filter:"+[NLog.Web]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -oldstyle -mergeoutput -output:coverage.xml
Loading coverage file C:\projects\nlogweb\coverage.xml
Failed to load coverage file C:\projects\nlogweb\coverage.xml
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at OpenCover.Framework.Model.InstrumentationPoint.ResetAfterLoading() in C:\projects\opencover\main\OpenCover.Framework\Model\InstrumentationPoint.cs:line 38
   at OpenCover.Framework.Persistance.BasePersistance.ReassignCoverageSession(CoverageSession session) in C:\projects\opencover\main\OpenCover.Framework\Persistance\BasePersistance.cs:line 127
   at OpenCover.Framework.Persistance.FilePersistance.LoadCoverageFile() in C:\projects\opencover\main\OpenCover.Framework\Persistance\FilePersistance.cs:line 119
Executing: C:\Tools\xUnit20\xunit.console.x86.exe
xUnit.net Console Runner (32-bit .NET 4.0.30319.42000)
  Discovering: NLog.Web.AspNetCore.Tests
  Discovered:  NLog.Web.AspNetCore.Tests
  Starting:    NLog.Web.AspNetCore.Tests
  Finished:    NLog.Web.AspNetCore.Tests
=== TEST EXECUTION SUMMARY ===
   NLog.Web.AspNetCore.Tests  Total: 134, Errors: 0, Failed: 0, Skipped: 0, Time: 1.566s
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

See https://ci.appveyor.com/project/nlog/nlog-web/builds/27482524

**Comment by 304NotModified** [comment]
Fixed in Azure pipleline
