### ISSUE TITLE
Net Core 3.1 Nlog Issue  (using MySQL)

### ISSUE THREAD

**Issue by ronaldo-o-reis** [NLog/NLog.Web#555]
I am trying to migrate from Net Core 2.2 to Net Core 3.1

After solving a lot of problem I have this one and was unable to find solution until now.

The exception is:

**2020-05-05 15:08:52.2508 Warn Type load exception. Exception: System.TypeLoadException: Could not load type 'System.Web.IHttpModule' from assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
2020-05-05 15:08:53.3247 Error DatabaseTarget(Name=allDb_wrapped): Error when writing to database. Exception: System.IO.FileNotFoundException: Could not load file or assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'. The system cannot find the file specified.
File name: 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.Driver.LoadServerProperties(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString, LogEventInfo logEventInfo)
   at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString, LogEventInfo logEventInfo)
   at NLog.Targets.DatabaseTarget.WriteLogEventToDatabase(LogEventInfo logEvent, String connectionString)**

I have added the extension to nlog-config:

`<extensions>
    <add assembly="NLog.Web" />
    <add assembly="NLog.Web.AspNetCore" />
  </extensions>`

Any thoughts?

**Comment by ronaldo-o-reis** [comment]
> Don't include NLog.Web. That's for ASP.NET non-core only.
> 
> So only include NLog.Web.AspNetCore

Originally, only NLog.Web.AspNetCore was include with the same error. I added Nlog.Web as an attempt to solve the issue

**Comment by 304NotModified** [comment]
Please update the error massages then.

**Comment by ronaldo-o-reis** [comment]
> Please update the error messages then.

Using extension as follows:

`  <extensions>
    <add assembly="NLog.Web.AspNetCore" />
  </extensions>
  `

The error is:

**2020-05-05 15:09:09.6825 Error AsyncWrapper(Name=allDb): Error in lazy writer timer procedure. Exception: NLog.NLogRuntimeException: Exception occurred in NLog
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'. The system cannot find the file specified.
File name: 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.Driver.LoadServerProperties(MySqlConnection connection)
   at MySql.Data.MySqlClient.Driver.Configure(MySqlConnection connection)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at NLog.Targets.DatabaseTarget.OpenConnection(String connectionString, LogEventInfo logEventInfo)
   at NLog.Targets.DatabaseTarget.EnsureConnectionOpen(String connectionString, LogEventInfo logEventInfo)
   at NLog.Targets.DatabaseTarget.WriteLogEventToDatabase(LogEventInfo logEvent, String connectionString)
   at NLog.Targets.DatabaseTarget.WriteLogEventsToDatabase(IList`1 logEvents, String connectionString)


   --- End of inner exception stack trace ---
   at NLog.LoggerImpl.<>c__DisplayClass1_0.<Write>b__1(Exception ex)
   at NLog.Internal.SingleCallContinuation.Function(Exception exception)
   at NLog.Targets.DatabaseTarget.WriteLogEventsToDatabase(IList`1 logEvents, String connectionString)
   at NLog.Targets.DatabaseTarget.Write(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncThreadSafe(IList`1 logEvents)
   at NLog.Targets.Target.WriteAsyncLogEvents(IList`1 logEvents)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.WriteEventsInQueue(Int32 batchSize, String reason)
   at NLog.Targets.Wrappers.AsyncTargetWrapper.ProcessPendingEvents(Object state)**

Cheers

**Comment by 304NotModified** [comment]
Which MySQL package you using and what nuget version?

**Comment by ronaldo-o-reis** [comment]
> Which MySQL package you using and what nuget version?

These below are related to MySQL

`<PackageReference Include="MySql.Data" Version="8.0.20" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" />`

**Comment by snakefoot** [comment]
@ronaldo-o-reis  Do you have anything in your application called "DotNetAgent" ?

Very strange that Google-search-engine has never heard about an assembly called "DotNetAgent" with `PublicKeyToken=87b69d96e75fbfca`

**Comment by ronaldo-o-reis** [comment]
> @ronaldo-o-reis Do you have anything in your application called "DotNetAgent" ?
> 
> Very strange that Google-search-engine has never heard about an assembly called "DotNetAgent" with `PublicKeyToken=87b69d96e75fbfca` (Guessing it is not part of MySql.Data)
> 
> Maybe try using Fusion++ https://github.com/awaescher/Fusion to see why "DotNetAgent" cannot load (Double-click the assembly-loading error to see more details).

No, there's nothing called DotNetAgent. That's why it is weird.

The error seems to occur due an attempt to write logs to the data base.

The project works running on VS 2019 (IIS Express) but fails at server using real IIS.

I am runnig out ideas...

**Comment by 304NotModified** [comment]
> Do you have anything in your application called "DotNetAgent" ?

I think that's from elastic? https://github.com/elastic/apm-agent-dotnet?

**Comment by 304NotModified** [comment]
> The project works running on VS 2019 (IIS Express) but fails at server using real IIS.

Please double check the bin folder of you start project local (where it works), and after publish (IIS folder)

**Comment by ronaldo-o-reis** [comment]
> > The project works running on VS 2019 (IIS Express) but fails at server using real IIS.
> 
> Please double check the bin folder of you start project local (where it works), and after publish (IIS folder)

Positively sure there's no elastic reference.

**Comment by 304NotModified** [comment]
Could you try without `<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" /> ` 

don't forget to clean all bin and maybe also obj folders. Powershell: `  gci -inc bin,obj -rec | rm -rec -force`

**Comment by ronaldo-o-reis** [comment]
> Could you try without `<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="3.1.1" /> `
> 
> don't forget to clean all bin and maybe also obj folders. Powershell: ` gci -inc bin,obj -rec | rm -rec -force`

Pomelo.EntityFrameworkCore.MySql is a MySQL provider for Entity Framework Core since Microsoft only cares about SqlServer. The project won't even compile without it.

Anyway, after cleaning the project I got other error messages not related to MySQL, so, I suppose there's nothing directly related to NLog _per se_.

An error message example:

**System.IO.FileNotFoundException: Could not load file or assembly 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'. The system cannot find the file specified.
File name: 'DotNetAgent, Version=1.0.0.0, Culture=neutral, PublicKeyToken=87b69d96e75fbfca'
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.PostAsync(Uri requestUri, HttpContent content)
   at P4F_Shared.Helpers.WebRequestHelper.WebRequestInnerCall(String baseUrl, IDictionary`2 headerItems, HttpRequestMessage request, String method) in ...**

I appreciate your help!! 

Thanks

**Comment by 304NotModified** [comment]
If I read this (but I don't use MySql)

https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html

I don't see any need for Pomelo.EntityFrameworkCore.MySql?

![image](https://user-images.githubusercontent.com/5808377/81178841-1a32c000-8fa9-11ea-9cc2-b6c320323f2e.png)

![image](https://user-images.githubusercontent.com/5808377/81178908-320a4400-8fa9-11ea-9906-a1107a99f0cc.png)

**Comment by ronaldo-o-reis** [comment]
> If I read this (but I don't use MySql)
> 
> https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework-core.html
> 
> I don't see any need for Pomelo.EntityFrameworkCore.MySql?
> 
> ![image](https://user-images.githubusercontent.com/5808377/81178841-1a32c000-8fa9-11ea-9cc2-b6c320323f2e.png)
> 
> ![image](https://user-images.githubusercontent.com/5808377/81178908-320a4400-8fa9-11ea-9906-a1107a99f0cc.png)

Yeah, for MySQL Pomelo makes the bridge between MySQL database and Microsoft EntityFramework.

**Comment by snakefoot** [comment]
Have not seen any issues when running NLog on NetCore31. 

Do not think your NetCore31 issues are coming from NLog, but from some other dependency. Especially when the assembly-resolve errors also occur on `HttpMessageInvoker.SendAsync`
