### ISSUE TITLE
MicrosoftConsoleLayout throws exception in MVC project

### ISSUE THREAD

**Issue by tometchy** [NLog/NLog.Web#755]
**Type**: Bug

**NLog version**: 4.7.13

**NLog.Web.AspNetCore version**: 4.14.0 

**NLog.Extensions.Logging version**: --

**Platform**: .Net 6

**Current NLog config**:
``` xml
<?xml version="1.0" encoding="utf-8" ?>
<!-- XSD manual extracted from package NLog.Schema: https://www.nuget.org/packages/NLog.Schema-->
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xsi:schemaLocation="NLog NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogFile="c:\temp\nlog-internal.log"
      internalLogLevel="Info" >

  <targets>
    <target xsi:type="Console" name="consoleTarget" layout="${MicrosoftConsoleLayout}" />
  </targets>

  <rules>
    <logger name="*" minlevel="Trace" writeTo="consoleTarget" />
  </rules>
</nlog>
```

Csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
    
  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.13" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.14.0" />
  </ItemGroup>

</Project>
```

Program.cs:
``` csharp
using NLog;
using NLog.Web;
using Microsoft.AspNetCore.Mvc;

var logger = NLog.LogManager.Setup().LoadConfigurationFromAppSettings().GetCurrentClassLogger();
logger.Debug("init main");

try
{
    var builder = WebApplication.CreateBuilder(args);
    
    builder.Services.AddControllersWithViews(); // <= Comment this out and the exception will no longer appear

    builder.Logging.ClearProviders();
    builder.Logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Trace);
    builder.Host.UseNLog();

    var app = builder.Build();

    app.Run();
}
catch (Exception exception)
{
    logger.Error(exception, "Stopped program because of exception");
    throw;
}
finally
{
    // Ensure to flush and stop internal timers/threads before application-exit (Avoid segmentation fault on Linux)
    NLog.LogManager.Shutdown();
}
```

In above configuration everything seems to work, yet I've noticed in internal nlog logs bellow exception:
```
2022-02-08 13:00:22.7356 Info Message Template Auto Format enabled
2022-02-08 13:00:22.7722 Info Adding target ConsoleTarget(Name=consoleTarget)
2022-02-08 13:00:22.8019 Info Validating config: TargetNames=consoleTarget, ConfigItems=4, FilePath=C:\Users\tom\Downloads\tempnlog\MinApi\bin\Debug\net6.0\NLog.config
2022-02-08 13:00:22.9913 Warn Exception in layout renderer. Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NLog.Extensions.Logging.MicrosoftConsoleLayoutRenderer.ConvertEventId(Int32 eventId)
   at NLog.Extensions.Logging.MicrosoftConsoleLayoutRenderer.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2022-02-08 13:00:23.0582 Warn Exception in layout renderer. Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NLog.Extensions.Logging.MicrosoftConsoleLayoutRenderer.ConvertEventId(Int32 eventId)
   at NLog.Extensions.Logging.MicrosoftConsoleLayoutRenderer.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
2022-02-08 13:00:23.0725 Warn Exception in layout renderer. Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NLog.Extensions.Logging.MicrosoftConsoleLayoutRenderer.ConvertEventId(Int32 eventId)
   at NLog.Extensions.Logging.MicrosoftConsoleLayoutRenderer.Append(StringBuilder builder, LogEventInfo logEvent)
   at NLog.LayoutRenderers.LayoutRenderer.RenderAppendBuilder(LogEventInfo logEvent, StringBuilder builder)
```

I have investigated that it doesn't happen when I don't use _MicrosoftConsoleLayout_, moreover, it also doesn't happen without `builder.Services.AddControllersWithViews()` line.

**Comment by snakefoot** [comment]
You are waiting for this pull-requests to be released with NLog 5.0 RTM (In 2 weeks time):
- https://github.com/NLog/NLog.Extensions.Logging/pull/570

Until then you must replace this:

```xml
  <targets>
    <target xsi:type="Console" name="consoleTarget" layout="${MicrosoftConsoleLayout}" />
  </targets>
```

With this:

```xml
  <variable name="MicrosoftLevel" value="${level:lowercase=true:truncate=4:when=level==LogLevel.Info or level==LogLevel.Warn}${when:when=level==LogLevel.Error:inner=fail}${when:when=level==LogLevel.Fatal:inner=crit}${when:when=level==LogLevel.Debug:inner=dbug}${when:when=level==LogLevel.Trace:inner=trce}" />
  <variable name="MicrosoftLayout" value="${MicrosoftLevel}: ${logger}[${event-properties:EventId_Id:whenEmpty=0}]${newline}      ${message}${onexception:inner=${newline}${exception:format=tostring}}" />

  <targets>
    <target xsi:type="Console" name="consoleTarget" layout="${MicrosoftLayout}" />
  </targets>
```

Sorry about the inconvience.

**Comment by tometchy** [comment]
Ok, thanks for the reply :)

**Comment by snakefoot** [comment]
NLog 5.0 RTM is finally here: https://www.nuget.org/packages/NLog
