### ISSUE TITLE
AspNetCore: AspNetUserIdentityLayoutRenderer throws an exception when retrieving Identity.Name

### ISSUE THREAD

**Issue by vcaraulean** [NLog/NLog.Web#83]
Error can be observed only with `throwExceptions="true"`. In this case, exception is thrown and Kestrel shuts down connection.

Target configuration:

    <target xsi:type="File" name="appFileTarget" fileName="${basedir}/logs/log-${shortdate}.log"
            layout="${longdate}|${uppercase:${level}}|${aspnet-user-identity}|${logger}|${message} ${exception}" />

Packages:

    "NLog": "4.4.1",
    "NLog.Web.AspNetCore": "4.2.4",
    "NLog.Extensions.Logging": "1.0.0-rtm-alpha5",

SDK:

    "sdk": {
      "version": "1.0.0-preview2-1-003177"
    }

Stack Trace of innermost exception:

    System.ObjectDisposedException: Safe handle has been closed
       at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
       at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
       at Microsoft.Win32.Win32Native.GetTokenInformation(SafeAccessTokenHandle TokenHandle, UInt32 TokenInformationClass, SafeLocalAllocHandle TokenInformation, UInt32 TokenInformationLength, UInt32& ReturnLength)
       at System.Security.Principal.WindowsIdentity.GetTokenInformation(SafeAccessTokenHandle tokenHandle, TokenInformationClass tokenInformationClass)
       at System.Security.Principal.WindowsIdentity.get_User()
       at System.Security.Principal.WindowsIdentity.GetName()
       at System.Security.Principal.WindowsIdentity.get_Name()
       at NLog.Web.LayoutRenderers.AspNetUserIdentityLayoutRenderer.DoAppend(StringBuilder builder, LogEventInfo logEvent)
       at NLog.LayoutRenderers.LayoutRenderer.Render(StringBuilder builder, LogEventInfo logEvent)
       at NLog.Layouts.SimpleLayout.GetFormattedMessage(LogEventInfo logEvent)
       at NLog.Targets.FileTarget.GetFormattedMessage(LogEventInfo logEvent)
       at NLog.Targets.FileTarget.GetBytesToWrite(LogEventInfo logEvent)
       at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
       at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
       at NLog.Targets.Target.WriteAsyncThreadSafe(AsyncLogEventInfo logEvent)
       at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
       at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
       at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
       at NLog.Logger.Log(LogEventInfo logEvent)
       at NLog.Extensions.Logging.NLogLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
       at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)

Our application is using WindowsAuthentication. User's Identity is not replaced, only an additional identity is added to the principal.

Strangest thing, it happens after few messages were already successfully logged.

Will try later to reproduce in a sample project.

**Comment by vcaraulean** [comment]
I suppose, with `throwExceptions="false"` messages will be just dropped down, right?

**Comment by vcaraulean** [comment]
I prepared a demo project here: https://github.com/vcaraulean/NLog.Web.AspNetCore.Issue83
It's a standard Asp.NET Core running on full .NET FW 4.6.

To get running:
 - install latest .NET Core SDK (1.1)
 - clone
 - `dotnet restore` in solution's folder
 - open solution in VS2015
 - F5

To reproduce, try navigating between pages (home, about, contacts). You should see errors popping in Output window and requests are not returned to the browser.

**Comment by vcaraulean** [comment]
From my (probably limited) understanding of situation:
 - asp.net is setting principal during request handling
 - when request completes, principal is disposed
 - and then nlog tries to write asynchronously to a target and retrieves WindowsIdentity.Name whose principal disposed already.

**Comment by 304NotModified** [comment]
> From my (probably limited) understanding of situation:
> 
> asp.net is setting principal during request handling
> when request completes, principal is disposed
> and then nlog tries to write asynchronously to a target and retrieves WindowsIdentity.Name whose principal disposed already.

That sounds plausibel if you would write async. This isn't the case here? (only checked the nlog.config ATM)

**Comment by vcaraulean** [comment]
I created a simple ASP.NET's logger implementation, to play/debug the problem in same sample project

To crash is as easy as:

        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
        {
            var user = _httpContextAccessor.HttpContext?.User?.Identity.Name;
            var message = formatter(state, exception);
            Debug.WriteLine($"================= {user ?? "<n/a>"}: {message}");
        }

**Comment by vcaraulean** [comment]
Asked for help and guidance on [aspnet/logging repo](https://github.com/aspnet/Logging/issues/543)

**Comment by 304NotModified** [comment]
:+1+

**Comment by 304NotModified** [comment]
I guess I have to add a `catch(ObjectDisposedException)`  - no movement in https://github.com/aspnet/Logging/issues/543 :|

**Comment by aravindk777** [comment]
is this still an issue? From the perspective of trying to log the current windows/httpcontext.User value in the log? I am using asp.net core 2.2x and configuring the nlog via Json configuration. below is how i setup the config.

"NLog": { "throwConfigExceptions": true, "extensions": [ { "assembly": "NLog.Extensions.Logging" }, { "assembly": "NLog.Web.AspNetCore" } ], "targets": { "apilogfile": { "type": "File", "fileName": "C:\\Logs\\MyApi.App\\ApiLog.log", "layout": "${date:format=yyyy-MM-dd-hh\\:mm\\:ss} ${level} ${machinename} ${aspnet-user-identity} - ${logger}: ${message} ${exception:format=tostring} ${exception:format=stackTrace} ${exception:format=InnerException}" }, "logconsole": { "type": "Console" } }, "rules": [ { "logger": "*", "minLevel": "Info", "writeTo": "logconsole" }, { "logger": "*", "minLevel": "Debug", "writeTo": "apilogfile" } ] },
with this, the log gets created with empty for the ${aspnet-user-identity}.

Note - this is a .net core 2.2 based web api, and i have hosted this in IIS, enabled the Windows authentication. This is being called by angular app, and that has also enabled with "withCredentials: true" in the request options. The auth is working and picking the user but the intent is to log the current user who is accessing the api to be logged. If that is not achievable by ${aspnet-user-identity} then which attr prop would allow to log the current logged on user / windows user / HttpContext.User.Identity to be exact.
